# This workflow is triggered by a push to the `main` branch
# which it checks out, runs cavern to process the svx files,
# and the pushes the results to the `build` branch.

name: svx-to-3d
run-name: Process SVX to 3D

# Run on pushed to `main` branch
on:
  push:
    branches:
      - main

jobs:
  checkout-and-process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install survex
      - run: sudo apt-get install -y survex

      # Run cavern to process the svx files
      - name: Process svx files
        run: |
          cavern Survex/pell.svx
          rm pell.err
          install -D pell.3d docs/surveys/pell.3d
          rm pell.3d

      # Re-download CaveView for docs
      - name: Download CaveView
        run: |
          rm -rf docs/CaveView
          wget https://github.com/aardgoose/CaveView.js/releases/latest/download/CaveView.zip -O docs/CaveView.zip
          unzip docs/CaveView.zip -d docs/
          rm docs/CaveView.zip

      # Push the results to the `build` branch
      - name: Push to build branch
        run: |
          git config user.name aricooperdavis
          git config user.email aricooperdavis@user.noreply.github.com
          git add .
          git commit -m 'Automated build of ${{ github.sha }}'
          git push --force -u origin main:build
