# This workflow is triggered by a push to the `main` branch
# which it checks out, runs therion to process the survey data,
# and the pushes the results to the `build` branch.

name: build-survey
run-name: Run therion on survey data

# Run on pushed to `main` branch
on:
  push:
    branches:
      - main

jobs:
  checkout-and-process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare for GH Pages build
        run: |
          install -D Therion/pell-plan.pdf docs/surveys/pell-plan.pdf
          install -D Therion/pell-plan.pdf docs/surveys/pell-elevation.pdf
          install -D Therion/pell.3d docs/surveys/pell.3d

      - name: Push changes
        run: |
          echo "Updating build branch"
          git config user.name aricooperdavis
          git config user.email aricooperdavis@user.noreply.github.com
          git add .
          git commit -m 'Automated build of ${{ github.sha }}' || echo "No changes to commit"
          git push --force -u origin main:build || echo "No changes to push"
