# This workflow is triggered by a push to the `main` branch
# which it checks out, runs cavern to process the svx files,
# and the pushes the results to the `build` branch.

name: svx-to-3d
run-name: Process SVX to 3D

# Run on pushed to `main` branch
on:
  push:
    branches:
      - main

jobs:
  checkout-and-process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare for GH Pages build
        run: |
          rm -rf docs/CaveView docs/surveys
          git checkout origin/build -- docs/CaveView docs/surveys || echo "Error checking out files from build branch"

          updated_at=""
          for f in $(find Survex/ -name '*.svx'); do
            commited_at=$(git log -1 --format=%ct -- $f)
            if [ -z "$updated_at" ] || [ "$commited_at" \> "$updated_at" ]; then
              updated_at="$commited_at"
            fi
          done

          if [ ! -f docs/surveys/pell.3d ] || [ $updated_at > git log -1 --format=%ct -- docs/surveys/pell.3d ]; then
            echo "Processing survey to reflect updates to Survex files"
            sudo apt-get install -y survex
            cavern Survex/pell.svx
            rm pell.err
            install -D pell.3d docs/surveys/pell.3d
            rm pell.3d
            changes=true
          else 
            echo "Survey is up to date with Survex files"
          fi

          if [ -d docs/CaveView ]; then
            local=$(gawk -F "'" '/VERSION =/{print $2}' docs/CaveView/js/CaveView2.js)
            remote=$(curl -sv https://api.github.com/repos/aardgoose/CaveView.js/releases/latest | jq -r '.name')
          fi
          if [ -z "$local"] || [ "$local" != "$remote" ]; then
            echo "Updating CaveView from $local to $remote"
            rm -rf docs/CaveView
            wget https://github.com/aardgoose/CaveView.js/releases/latest/download/CaveView.zip -O docs/CaveView.zip
            unzip docs/CaveView.zip -d docs/
            rm docs/CaveView.zip
            changes=true
          else
            echo "Local CaveView version $local is up to date"
          fi

      - name: Push changes
        run: |
          echo "Updating build branch"
          git config user.name aricooperdavis
          git config user.email aricooperdavis@user.noreply.github.com
          git add .
          git commit -m 'Automated build of ${{ github.sha }}' || echo "No changes to commit"
          git push --force -u origin main:build || echo "No changes to push"
